### ISSUE TITLE
FPP to Dictionary

### ISSUE THREAD

**Issue by jwest115** [nasa/fprime#2263]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Build a tool that outputs the dictionary to one of two formats: json or yml

Sub-tasks include:
1. [x] Create spec/SDD of JSON format, tighten up the FPP spec. Ensure that we have a complete representation of FPP model elements in JSON - #2275
2. [x] Create scala data structure for the dictionary (so that we can compute the dictionary for each topology) - #2274 
3. [x] JSON generation for dictionary - #2479
3. [x] Create utility in FPP tools that does the fpp-to-dict - #2276
4. [x] Write unit tests for fpp-to-dict tool - #2501

**Comment by thomas-bc** [comment]
PR merged in FPP - to be integrated in CMake/GDS.
All tickets are linked above
