### ISSUE TITLE
Add Baremetal Reference to CI

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2614]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

The goal of this epic issue is to run the [fprime-baremetal-reference](https://github.com/fprime-community/fprime-baremetal-reference) with HIL testing via our Github Actions.  

This breaks down into several steps:

- [x] https://github.com/nasa/fprime/issues/2611
- [x] https://github.com/nasa/fprime/issues/2612
- [ ] https://github.com/nasa/fprime/issues/2613

**Comment by capsulecorplab** [comment]
Currently attempting [this](https://github.com/fprime-community/fprime-workspace-image/issues/40) on the [fprime-workspace-image](https://github.com/fprime-community/fprime-workspace-image). Can follow progress on https://github.com/fprime-community/fprime-workspace-image/pull/53

**Comment by LeStarch** [comment]
Need to add to CI in nasa/fprime
